language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install flake8 coverage codecov
  - pip install -r requirements.txt

script:
  - coverage run -m pytest
  - flake8

after_success:
  - codecov